using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;
using System.Linq;
using FitnessTracker.Models;

namespace FitnessTracker.Services
{
    public class WgerService : IWgerService
    {
        public WgerService()
        {
        }

        private static readonly List<string> topExercises = new List<string>
        {
            // Use the exerciseinfo endpoint which includes translations.
            // translation contains the exercise name for a specific language.
           
            "Running",
            "Walking",
            "Cycling",
            "Swimming",
            "Soccer (Football)",
            "Basketball",
            "Tennis",
            "Volleyball",
            "Baseball",
            "Rugby",
            "Cricket",
            "Badminton",
            "Table Tennis",
            "Squash",
            "Golf",
            "Boxing",
            "Mixed Martial Arts",
            "Wrestling",
            "Judo",
            "Karate",
            "Kickboxing",
            "Pilates",
            "Yoga",
            "CrossFit",
            "High-Intensity Interval Training (HIIT)",
            "Weightlifting",
            "Powerlifting",
            "Olympic Weightlifting",
            "Bench Press",
            "Deadlift",
            "Squat",
            "Overhead Press",
            "Pull-Up",
            "Chin-Up",
            "Push-Up",
            "Dip",
            "Lunge",
            "Plank",
            "Crunch",
            "Sit-Up",
            "Burpee",
            "Mountain Climbers",
            "Russian Twist",
            "Bicycle Crunch",
            "Leg Raise",
            "Back Extension",
            "Superman",
            "Side Plank",
            "Bird Dog",
            "Box Jump",
            "Jump Rope",
            "Kettlebell Swing",
            "Kettlebell Snatch",
            "Turkish Get-Up",
            "Battle Ropes",
            "Sled Push",
            "Sled Pull",
            "Farmer's Walk",
            "Sandbag Carry",
            "Rowing Machine",
            "Elliptical Trainer",
            "Stair Climber",
            "Hiking",
            "Trail Running",
            "Skateboarding",
            "Rollerblading",
            "Skiing (Downhill)",
            "Skiing (Cross-Country)",
            "Snowboarding",
            "Snowshoeing",
            "Ice Skating",
            "Rock Climbing (Outdoor)",
            "Rock Climbing (Indoor)",
            "Surfing",
            "Paddleboarding",
            "Kayaking",
            "Canoeing",
            "Stand-Up Paddleboarding",
            "Archery",
            "Fencing",
            "Gymnastics",
            "Dance (Zumba)",
            "Ballet",
            "Aerobics (General)",
            "Step Aerobics",
            "Bodypump (Barbell Class)",
            "TRX Suspension Training",
            "Circuit Training",
            "Functional Training",
            "Agility Ladder Drills",
            "Sprinting",
            "Interval Training",
            "Tabata",
            "Tai Chi",
            "Qigong",
            "Martial Arts Conditioning",
            "Wheelchair Basketball",
            "Adaptive CrossFit",
            "Water Aerobics",
            "Aqua Jogging",
            "Treadmill Running",
            "Treadmill Incline Walking",
            "Treadmill Sprint Intervals",
            "Recumbent Biking",
            "Spin Class",
            "Air Bike",
            "Ski Erg",
            "Row Machine (erg)",
            "Seated Row Machine",
            "Lat Pulldown Machine",
            "Chest Press Machine",
            "Leg Press Machine",
            "Leg Curl Machine",
            "Leg Extension Machine",
            "Smith Machine Squat",
            "Hack Squat Machine",
            "Hip Abduction Machine",
            "Hip Adduction Machine",
            "Calf Raise Machine",
            "Pec Deck Fly Machine",
            "Cable Crossover",
            "Smith Machine Bench Press",
            "Smith Machine Shoulder Press",
            "Assisted Pull-Up Machine",
            "Assisted Dip Machine",
            "Glute Bridge",
            "Single-Leg Glute Bridge",
            "Hip Thrust",
            "Bulgarian Split Squat",
            "Pistol Squat",
            "Step-Up",
            "Box Step-Up",
            "Weighted Step-Up",
            "Goblet Squat",
            "Front Squat",
            "Back Squat",
            "Overhead Squat",
            "Zercher Squat",
            "Sumo Deadlift",
            "Romanian Deadlift",
            "Stiff-Legged Deadlift",
            "Snatch-Grip Deadlift",
            "Trap Bar Deadlift",
            "Power Clean",
            "Hang Clean",
            "Clean and Jerk",
            "Snatch",
            "Push Press",
            "Push Jerk",
            "Split Jerk",
            "Military Press",
            "Dumbbell Shoulder Press",
            "Arnold Press",
            "Lateral Raise",
            "Front Raise",
            "Rear Delt Fly",
            "Upright Row",
            "Face Pull",
            "Shrug",
            "Barbell Row",
            "Single-Arm Dumbbell Row",
            "T-Bar Row",
            "Inverted Row",
            "Cable Row",
            "Chest Fly (Dumbbell)",
            "Chest Fly (Machine)",
            "Incline Dumbbell Bench Press",
            "Decline Bench Press",
            "Dumbbell Bench Press",
            "Weighted Dip",
            "Weighted Pull-Up",
            "Neutral-Grip Pull-Up",
            "Wide-Grip Pull-Up",
            "Narrow-Grip Pull-Up",
            "Commando Pull-Up",
            "Clap Push-Up",
            "Plyometric Push-Up",
            "Diamond Push-Up",
            "Wide Push-Up",
            "Incline Push-Up",
            "Decline Push-Up",
            "Handstand Push-Up",
            "Pike Push-Up",
            "Spiderman Push-Up",
            "Archer Push-Up",
            "Clap Pull-Up",
            "Muscle-Up",
            "Ring Dip",
            "Ring Row",
            "TRX Row",
            "TRX Chest Press",
            "TRX Tricep Extension",
            "TRX Bicep Curl",
            "TRX Pike",
            "TRX Atomic Push-Up",
            "Nordic Hamstring Curl",
            "Hamstring Curl (Machine)",
            "Reverse Hyperextension",
            "Glute-Ham Raise",
            "Calf Raise (Standing)",
            "Calf Raise (Seated)",
            "Toe Raise",
            "Tibialis Raise",
            "Ab Wheel Rollout",
            "Hanging Leg Raise",
            "Captain's Chair Leg Raise",
            "Flutter Kicks",
            "Scissor Kicks",
            "V-Up",
            "L-Sit",
            "Dragon Flag",
            "Stability Ball Rollout",
            "Stability Ball Crunch",
            "Stability Ball Pike",
            "Medicine Ball Slam",
            "Medicine Ball Russian Twist",
            "Medicine Ball Overhead Throw",
            "Medicine Ball Chest Pass",
             "Slam Ball Overhead Throw",
            "Battle Rope Alternating Waves",
            "Battle Rope Double Wave",
            "Battle Rope Slams",
            "Sandbag Clean",
            "Sandbag Shoulder Carry",
            "Sandbag Overhead Press",
            "Sandbag Deadlift",
            "Sled Drag",
            "Sled Row",
            "Yoke Walk",
            "Log Press",
            "Atlas Stone Lift",
            "Tire Flip",
            "Box Tire Flip",
            "Rope Climb",
            "Rope Pull",
            "Farmers Carry (Dumbbell)",
            "Suitcase Carry",
            "Waiter Carry",
            "Kettlebell Carry",
            "Depth Jump",
            "Broad Jump",
            "Skater Hops",
            "Split Squat Jump",
            "Lateral Bound",
            "Tuck Jump",
            "Sledgehammer Slam",
            "Vinyasa Yoga",
            "Ashtanga Yoga",
            "Yin Yoga",
            "Restorative Yoga"
        };

        private static readonly List<ExerciseDto> _exercises = topExercises
            .Select((name, index) => new ExerciseDto
            {
                Id = index + 1,
                Name = name,
                NameOriginal = name
            })
            .ToList();

        public Task<IEnumerable<ExerciseDto>> GetExercisesAsync(int page = 1)
        {
            // Ignore paging since we return a fixed list.
            return Task.FromResult<IEnumerable<ExerciseDto>>(_exercises);


        }
    }
}
